/* eslint-disable import/prefer-default-export */
export const specializationsMap = {
  0: { specialization: 'Agrarrecht' },
  1: { specialization: 'Allgemeines Vertragsrecht' },
  2: { specialization: 'Anwaltshaftung' },
  3: { specialization: 'Arbeitsrecht' },
  4: { specialization: 'Arzthaftungsrecht' },
  5: { specialization: 'Ausländerrecht & Asylrecht' },
  6: { specialization: 'Bankrecht & Kapitalmarktrecht' },
  7: { specialization: 'Baurecht & Architektenrecht' },
  8: { specialization: 'Beamtenrecht' },
  10: { specialization: 'Betriebliche Altersversorgung' },
  11: { specialization: 'Datenschutzrecht' },
  12: { specialization: 'Designrecht' },
  13: { specialization: 'Erbrecht' },
  14: { specialization: 'Familienrecht' },
  15: { specialization: 'Forderungseinzug & Inkassorecht' },
  16: { specialization: 'Gewerblicher Rechtsschutz' },
  17: { specialization: 'Grundstücksrechts & Immobilienrecht' },
  18: { specialization: 'Insolvenzrecht' },
  19: { specialization: 'Internationales Recht' },
  20: { specialization: 'Internationales Wirtschaftsrecht' },
  21: { specialization: 'IT-Recht' },
  22: { specialization: 'Jagdrecht' },
  23: { specialization: 'Kaufrecht' },
  24: { specialization: 'Maklerrecht' },
  25: { specialization: 'Markenrecht' },
  26: { specialization: 'Mediation' },
  27: { specialization: 'Medizinrecht' },
  28: { specialization: 'Mietrechts & Wohnungseigenturmsrecht' },
  29: { specialization: 'Migrationsrecht' },
  30: { specialization: 'Öffentliches Baurecht' },
  31: { specialization: 'Öffentliches Rechts' },
  32: { specialization: 'Opferhilfe' },
  33: { specialization: 'Ordnungswidrigkeitenrecht' },
  34: { specialization: 'Patentrecht' },
  35: { specialization: 'Pferderecht' },
  36: { specialization: 'Pflegerecht' },
  37: { specialization: 'Rechts rund ums Tier' },
  38: { specialization: 'Reiserecht' },
  39: { specialization: 'Schadensersatzrecht & Schmerzensgeldrecht' },
  40: { specialization: 'Schiedsgerichtsbarkeit' },
  41: { specialization: 'Schulrecht' },
  42: { specialization: 'Schwerbehindertenrecht' },
  43: { specialization: 'Sozialrecht' },
  44: { specialization: 'Sozialversicherungsrecht' },
  45: { specialization: 'Sportrecht' },
  46: { specialization: 'Steuerrecht' },
  47: { specialization: 'Strafrecht' },
  48: { specialization: 'Transportrecht & Speditionsrecht' },
  49: { specialization: 'Umweltrecht' },
  50: { specialization: 'Unterhaltsrecht' },
  51: { specialization: 'Unternehmensrecht & Betriebsnachfolge' },
  52: { specialization: 'Urheberrecht & Medienrecht' },
  53: { specialization: 'Vereinsrecht & Verbandsrecht' },
  54: { specialization: 'Verfassungsrecht' },
  55: { specialization: 'Vergaberecht' },
  56: { specialization: 'Verkehrsrecht' },
  57: { specialization: 'Versicherungsrecht' },
  58: { specialization: 'Verwaltungsrecht' },
  59: { specialization: 'Werkvertragsrecht' },
  60: { specialization: 'Wettbewerbsrecht' },
  61: { specialization: 'Wirtschaftsrecht' },
  62: { specialization: 'Zivilprozessrecht' },
  63: { specialization: 'Zivilrecht' },
  64: { specialization: 'Zwangsvollstreckungsrecht' },
  65: { specialization: 'Erbrecht' },
  66: { specialization: 'Familienrecht' },
  67: { specialization: 'Handelsrecht & Gesellschaftsrecht' },
  68: { specialization: 'Immobilienrecht' },
  69: { specialization: 'Vorsorgevollmacten' },
  70: { specialization: 'Sonstige Beglaubigungen & Beurkundung' },
};

export const languageMap = {
  1: { language: 'Arabisch' },
  2: { language: 'Englisch' },
  3: { language: 'Französisch' },
  4: { language: 'Gebärdensprache' },
  5: { language: 'Italienisch' },
  6: { language: 'Persisch' },
  7: { language: 'Polnisch' },
  8: { language: 'Portugiesisch' },
  9: { language: 'Rumänisch' },
  10: { language: 'Russisch' },
  11: { language: 'Spanisch' },
  12: { language: 'Türkisch' },
};

export const genderMap = {
  0: 'male',
  1: 'female',
  2: 'other',
};
