export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const SET_APPOINTMENT = 'SET_APPOINTMENT';
export const TOGGLE_CANCELLATION_MODAL = 'TOGGLE_CANCELLATION_MODAL';
export const SET_ACTIVE_USER_APPOINTMENT = 'SET_ACTIVE_USER_APPOINTMENT';
export const SET_ACTIVE_PAST_APPOINTMENT = 'SET_ACTIVE_PAST_APPOINTMENT';
