export const REGISTRATION_STEPS = {
  GET_STARTED: 'GET_STARTED',
  PERSONAL_DATA: 'PERSONAL_DATA',
  JOB_TITLE: 'JOB_TITLE',
  ADDRESS_ENTRY: 'ADDRESS_ENTRY',
  PASSWORD_SETTING: 'PASSWORD_SETTING',
  HOW_TO_USE: 'HOW_TO_USE',
  CONFIRMATION: 'CONFIRMATION',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  ACCOUNT_CONFIRMED: 'ACCOUNT_CONFIRMED',
};

export const GENDERS = {
  MALE: 0,
  FEMALE: 1,
};

export default {};
