export const REGISTRATION_STEPS = {
  GET_STARTED: 'GET_STARTED',
  PERSONAL_DATA: 'PERSONAL_DATA',
  JOB_TITLE: 'JOB_TITLE',
  ADDRESS_ENTRY: 'ADDRESS_ENTRY',
  PASSWORD_SETTING: 'PASSWORD_SETTING',
  HOW_TO_USE: 'HOW_TO_USE',
  TUTORIAL: 'TUTORIAL',
  CONFIRMATION: 'CONFIRMATION',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
};

export const GENDERS = {
  MALE: 'male',
  FEMALE: 'female',
};

export default {};
