export const LOGIN_USER = 'LOGIN_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const REGISTER_USER = 'REGISTER_USER';
export const DELETE_USER = 'DELETE_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const GET_USER_ID_FROM_TOKEN = 'GET_USER_ID_FROM_TOKEN';
export const SET_USER_ID_FROM_TOKEN = 'SET_USER_ID_FROM_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_USER_MESSAGE = 'SET_USER_MESSAGE';
export const REGISTER_EXPERT = 'REGISTER_EXPERT';
export const GET_VALIDITY_OF_CONFIRMATION_TOKEN =
  'GET_VALIDITY_OF_CONFIRMATION_TOKEN';
export const SET_VALIDITY_OF_CONFIRMATION_TOKEN =
  'SET_VALIDITY_OF_CONFIRMATION_TOKEN';
