export const MARKER_CLICK = 'MARKER_CLICK';
export const ON_MOUSE_ENTER_CARD = 'ON_MOUSE_ENTER_CARD';
export const ON_MOUSE_LEAVE_CARD = 'ON_MOUSE_LEAVE_CARD';
export const GET_LAWYERS = 'GET_LAWYERS';
export const SET_LAWYERS = 'SET_LAWYERS';
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_LANGUAGE_FILTERS = 'SET_LANGUAGE_FILTERS';
export const SET_SPECIALIZATION_FILTERS = 'SET_SPECIALIZATION_FILTERS';
export const SEARCH_BY_NAME_OR_FIRM_OR_LOCATION = 'SEARCH_BY_NAME_OR_FIRM_OR_LOCATION';
export const GET_SEARCH_SUGGESTIONS_FOR_NAME_OR_FIRM = 'GET_SEARCH_SUGGESTIONS_FOR_NAME_OR_FIRM';
export const GET_SEARCH_SUGGESTIONS_FOR_LOCATIONS = 'GET_SEARCH_SUGGESTIONS_FOR_LOCATIONS';
export const GET_LAWYER_AVAILABILITY = 'GET_LAWYER_AVAILABILITY';
export const SET_LAWYER_AVAILABILITY = 'SET_LAWYER_AVAILABILITY';
export const LOAD_LAWYER_AVAILABILITY = 'LOAD_LAWYER_AVAILABILITY';

export const specializations = {
  notarySpecializations: [
    { id: 112, specilization: 'Zivilprozessrecht', type: 2 },
    { id: 113, specilization: 'Zivilrecht', type: 2 },
    { id: 114, specilization: 'Zwangsvollstreckungsrecht', type: 2 },
    { id: 115, specilization: 'Erbrecht', type: 2 },
    { id: 116, specilization: 'Familienrecht', type: 2 },
    { id: 117, specilization: 'Handelsrecht & Gesellschaftsrecht', type: 2 },
    { id: 118, specilization: 'Immobilienrecht', type: 2 },
    { id: 119, specilization: 'Vorsorgevollmacten', type: 2 },
    {
      id: 120,
      specilization: 'Sonstige Beglaubigungen & Beurkundung',
      type: 2,
    },
  ],
  lawSpecializations: [
    { id: 1, specilization: 'Agrarrecht', type: 1 },
    { id: 2, specilization: 'Allgemeines Vertragsrecht', type: 1 },
    { id: 3, specilization: 'Anwaltshaftung', type: 1 },
    { id: 4, specilization: 'Arbeitsrecht', type: 1 },
    { id: 5, specilization: 'Arzthaftungsrecht', type: 1 },
    { id: 6, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
    { id: 7, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
    { id: 8, specilization: 'Baurecht & Architektenrecht', type: 1 },
    { id: 9, specilization: 'Beamtenrecht', type: 1 },
    { id: 10, specilization: 'Betreuungsrecht', type: 1 },
    { id: 11, specilization: 'Betriebliche Altersversorgung', type: 1 },
    { id: 12, specilization: 'Datenschutzrecht', type: 1 },
    { id: 13, specilization: 'Designrecht', type: 1 },
    { id: 14, specilization: 'Erbrecht', type: 1 },
    { id: 15, specilization: 'Familienrecht', type: 1 },
    { id: 16, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
    { id: 17, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
    { id: 18, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
    { id: 19, specilization: 'Insolvenzrecht', type: 1 },
    { id: 20, specilization: 'Internationales Recht', type: 1 },
    { id: 21, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
    { id: 22, specilization: 'IT-Recht', type: 1 },
    { id: 23, specilization: 'Jagdrecht', type: 1 },
    { id: 24, specilization: 'Kaufrecht', type: 1 },
    { id: 25, specilization: 'Maklerrecht', type: 1 },
    { id: 26, specilization: 'Markenrecht', type: 1 },
    { id: 27, specilization: 'Mediation', type: 1 },
    { id: 28, specilization: 'Medizinrecht', type: 1 },
    { id: 29, specilization: 'Mietrechts & Wohnungseigenturmsrecht', type: 1 },
    { id: 30, specilization: 'Migrationsrecht', type: 1 },
    { id: 31, specilization: 'Öffentliches Baurecht', type: 1 },
    { id: 32, specilization: 'Öffentliches Rechts', type: 1 },
    { id: 33, specilization: 'Opferhilfe', type: 1 },
    { id: 34, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
    { id: 35, specilization: 'Patentrecht', type: 1 },
    { id: 36, specilization: 'Pferderecht', type: 1 },
    { id: 37, specilization: 'Pflegerecht', type: 1 },
    { id: 38, specilization: 'Rechts rund ums Tier', type: 1 },
    { id: 39, specilization: 'Reiserecht', type: 1 },
    { id: 40, specilization: 'Schadensersatzrecht &', type: 1 },
    { id: 41, specilization: 'Schmerzensgeldrecht', type: 1 },
    { id: 42, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
    { id: 43, specilization: 'Secht', type: 1 },
    { id: 44, specilization: 'Schwerbehindertenrecht', type: 1 },
    { id: 45, specilization: 'Sozialrecht', type: 1 },
    { id: 46, specilization: 'Sozialversicherungsrecht', type: 1 },
    { id: 47, specilization: 'Sportrecht', type: 1 },
    { id: 48, specilization: 'Steuerrecht', type: 1 },
    { id: 49, specilization: 'StrafrechtAgrarrecht', type: 1 },
    { id: 50, specilization: 'Allgemeines Vertragsrecht', type: 1 },
    { id: 51, specilization: 'Anwaltshaftung', type: 1 },
    { id: 52, specilization: 'Arbeitsrecht', type: 1 },
    { id: 53, specilization: 'Arzthaftungsrecht', type: 1 },
    { id: 54, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
    { id: 55, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
    { id: 56, specilization: 'Baurecht & Architektenrecht', type: 1 },
    { id: 57, specilization: 'Beamtenrecht', type: 1 },
    { id: 58, specilization: 'Betreuungsrecht', type: 1 },
    { id: 59, specilization: 'Betriebliche Altersversorgung', type: 1 },
    { id: 60, specilization: 'Datenschutzrecht', type: 1 },
    { id: 61, specilization: 'Designrecht', type: 1 },
    { id: 62, specilization: 'Erbrecht', type: 1 },
    { id: 63, specilization: 'Familienrecht', type: 1 },
    { id: 64, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
    { id: 65, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
    { id: 66, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
    { id: 67, specilization: 'Insolvenzrecht', type: 1 },
    { id: 68, specilization: 'Internationales Recht', type: 1 },
    { id: 69, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
    { id: 70, specilization: 'IT-Recht', type: 1 },
    { id: 71, specilization: 'Jagdrecht', type: 1 },
    { id: 72, specilization: 'Kaufrecht', type: 1 },
    { id: 73, specilization: 'Maklerrecht', type: 1 },
    { id: 74, specilization: 'Markenrecht', type: 1 },
    { id: 75, specilization: 'Mediation', type: 1 },
    { id: 76, specilization: 'Medizinrecht', type: 1 },
    { id: 77, specilization: 'Mietrechts & Wohnungseigenturmsrecht', type: 1 },
    { id: 78, specilization: 'Migrationsrecht', type: 1 },
    { id: 79, specilization: 'Öffentliches Baurecht', type: 1 },
    { id: 80, specilization: 'Öffentliches Rechts', type: 1 },
    { id: 81, specilization: 'Opferhilfe', type: 1 },
    { id: 82, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
    { id: 83, specilization: 'Patentrecht', type: 1 },
    { id: 84, specilization: 'Pferderecht', type: 1 },
    { id: 85, specilization: 'Pflegerecht', type: 1 },
    { id: 86, specilization: 'Rechts rund ums Tier', type: 1 },
    { id: 87, specilization: 'Reiserecht', type: 1 },
    { id: 88, specilization: 'Schadensersatzrecht &', type: 1 },
    { id: 89, specilization: 'Schmerzensgeldrecht', type: 1 },
    { id: 90, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
    { id: 91, specilization: 'Secht', type: 1 },
    { id: 92, specilization: 'Schwerbehindertenrecht', type: 1 },
    { id: 93, specilization: 'Sozialrecht', type: 1 },
    { id: 94, specilization: 'Sozialversicherungsrecht', type: 1 },
    { id: 95, specilization: 'Sportrecht', type: 1 },
    { id: 96, specilization: 'Steuerrecht', type: 1 },
    { id: 97, specilization: 'Strafrecht', type: 1 },
    { id: 98, specilization: 'Transportrecht & Speditionsrecht', type: 1 },
    { id: 99, specilization: 'Umweltrecht', type: 1 },
    { id: 100, specilization: 'Unterhaltsrecht', type: 1 },
    {
      id: 101,
      specilization: 'Unternehmensrecht & Betriebsnachfolge',
      type: 1,
    },
    { id: 102, specilization: 'Urheberrecht & Medienrecht', type: 1 },
    { id: 103, specilization: 'Vereinsrecht & Verbandsrecht', type: 1 },
    { id: 104, specilization: 'Verfassungsrecht', type: 1 },
    { id: 105, specilization: 'Vergaberecht', type: 1 },
    { id: 106, specilization: 'Verkehrsrecht', type: 1 },
    { id: 107, specilization: 'Versicherungsrecht', type: 1 },
    { id: 108, specilization: 'Verwaltungsrecht', type: 1 },
    { id: 109, specilization: 'Werkvertragsrecht', type: 1 },
    { id: 110, specilization: 'Wettbewerbsrecht', type: 1 },
    { id: 111, specilization: 'Wirtschaftsrecht', type: 1 },
  ],
};

export const specializationsMap = {
  1: { id: 1, specilization: 'Agrarrecht', type: 1 },
  2: { id: 2, specilization: 'Allgemeines Vertragsrecht', type: 1 },
  3: { id: 3, specilization: 'Anwaltshaftung', type: 1 },
  4: { id: 4, specilization: 'Arbeitsrecht', type: 1 },
  5: { id: 5, specilization: 'Arzthaftungsrecht', type: 1 },
  6: { id: 6, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
  7: { id: 7, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
  8: { id: 8, specilization: 'Baurecht & Architektenrecht', type: 1 },
  9: { id: 9, specilization: 'Beamtenrecht', type: 1 },
  10: { id: 10, specilization: 'Betreuungsrecht', type: 1 },
  11: { id: 11, specilization: 'Betriebliche Altersversorgung', type: 1 },
  12: { id: 12, specilization: 'Datenschutzrecht', type: 1 },
  13: { id: 13, specilization: 'Designrecht', type: 1 },
  14: { id: 14, specilization: 'Erbrecht', type: 1 },
  15: { id: 15, specilization: 'Familienrecht', type: 1 },
  16: { id: 16, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
  17: { id: 17, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
  18: { id: 18, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
  19: { id: 19, specilization: 'Insolvenzrecht', type: 1 },
  20: { id: 20, specilization: 'Internationales Recht', type: 1 },
  21: { id: 21, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
  22: { id: 22, specilization: 'IT-Recht', type: 1 },
  23: { id: 23, specilization: 'Jagdrecht', type: 1 },
  24: { id: 24, specilization: 'Kaufrecht', type: 1 },
  25: { id: 25, specilization: 'Maklerrecht', type: 1 },
  26: { id: 26, specilization: 'Markenrecht', type: 1 },
  27: { id: 27, specilization: 'Mediation', type: 1 },
  28: { id: 28, specilization: 'Medizinrecht', type: 1 },
  29: {
    id: 29,
    specilization: 'Mietrechts & Wohnungseigenturmsrecht',
    type: 1,
  },
  30: { id: 30, specilization: 'Migrationsrecht', type: 1 },
  31: { id: 31, specilization: 'Öffentliches Baurecht', type: 1 },
  32: { id: 32, specilization: 'Öffentliches Rechts', type: 1 },
  33: { id: 33, specilization: 'Opferhilfe', type: 1 },
  34: { id: 34, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
  35: { id: 35, specilization: 'Patentrecht', type: 1 },
  36: { id: 36, specilization: 'Pferderecht', type: 1 },
  37: { id: 37, specilization: 'Pflegerecht', type: 1 },
  38: { id: 38, specilization: 'Rechts rund ums Tier', type: 1 },
  39: { id: 39, specilization: 'Reiserecht', type: 1 },
  40: { id: 40, specilization: 'Schadensersatzrecht &', type: 1 },
  41: { id: 41, specilization: 'Schmerzensgeldrecht', type: 1 },
  42: { id: 42, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
  43: { id: 43, specilization: 'Secht', type: 1 },
  44: { id: 44, specilization: 'Schwerbehindertenrecht', type: 1 },
  45: { id: 45, specilization: 'Sozialrecht', type: 1 },
  46: { id: 46, specilization: 'Sozialversicherungsrecht', type: 1 },
  47: { id: 47, specilization: 'Sportrecht', type: 1 },
  48: { id: 48, specilization: 'Steuerrecht', type: 1 },
  49: { id: 49, specilization: 'StrafrechtAgrarrecht', type: 1 },
  50: { id: 50, specilization: 'Allgemeines Vertragsrecht', type: 1 },
  51: { id: 51, specilization: 'Anwaltshaftung', type: 1 },
  52: { id: 52, specilization: 'Arbeitsrecht', type: 1 },
  53: { id: 53, specilization: 'Arzthaftungsrecht', type: 1 },
  54: { id: 54, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
  55: { id: 55, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
  56: { id: 56, specilization: 'Baurecht & Architektenrecht', type: 1 },
  57: { id: 57, specilization: 'Beamtenrecht', type: 1 },
  58: { id: 58, specilization: 'Betreuungsrecht', type: 1 },
  59: { id: 59, specilization: 'Betriebliche Altersversorgung', type: 1 },
  60: { id: 60, specilization: 'Datenschutzrecht', type: 1 },
  61: { id: 61, specilization: 'Designrecht', type: 1 },
  62: { id: 62, specilization: 'Erbrecht', type: 1 },
  63: { id: 63, specilization: 'Familienrecht', type: 1 },
  64: { id: 64, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
  65: { id: 65, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
  66: { id: 66, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
  67: { id: 67, specilization: 'Insolvenzrecht', type: 1 },
  68: { id: 68, specilization: 'Internationales Recht', type: 1 },
  69: { id: 69, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
  70: { id: 70, specilization: 'IT-Recht', type: 1 },
  71: { id: 71, specilization: 'Jagdrecht', type: 1 },
  72: { id: 72, specilization: 'Kaufrecht', type: 1 },
  73: { id: 73, specilization: 'Maklerrecht', type: 1 },
  74: { id: 74, specilization: 'Markenrecht', type: 1 },
  75: { id: 75, specilization: 'Mediation', type: 1 },
  76: { id: 76, specilization: 'Medizinrecht', type: 1 },
  77: {
    id: 77,
    specilization: 'Mietrechts & Wohnungseigenturmsrecht',
    type: 1,
  },
  78: { id: 78, specilization: 'Migrationsrecht', type: 1 },
  79: { id: 79, specilization: 'Öffentliches Baurecht', type: 1 },
  80: { id: 80, specilization: 'Öffentliches Rechts', type: 1 },
  81: { id: 81, specilization: 'Opferhilfe', type: 1 },
  82: { id: 82, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
  83: { id: 83, specilization: 'Patentrecht', type: 1 },
  84: { id: 84, specilization: 'Pferderecht', type: 1 },
  85: { id: 85, specilization: 'Pflegerecht', type: 1 },
  86: { id: 86, specilization: 'Rechts rund ums Tier', type: 1 },
  87: { id: 87, specilization: 'Reiserecht', type: 1 },
  88: { id: 88, specilization: 'Schadensersatzrecht &', type: 1 },
  89: { id: 89, specilization: 'Schmerzensgeldrecht', type: 1 },
  90: { id: 90, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
  91: { id: 91, specilization: 'Secht', type: 1 },
  92: { id: 92, specilization: 'Schwerbehindertenrecht', type: 1 },
  93: { id: 93, specilization: 'Sozialrecht', type: 1 },
  94: { id: 94, specilization: 'Sozialversicherungsrecht', type: 1 },
  95: { id: 95, specilization: 'Sportrecht', type: 1 },
  96: { id: 96, specilization: 'Steuerrecht', type: 1 },
  97: { id: 97, specilization: 'Strafrecht', type: 1 },
  98: { id: 98, specilization: 'Transportrecht & Speditionsrecht', type: 1 },
  99: { id: 99, specilization: 'Umweltrecht', type: 1 },
  100: { id: 100, specilization: 'Unterhaltsrecht', type: 1 },
  101: {
    id: 101,
    specilization: 'Unternehmensrecht & Betriebsnachfolge',
    type: 1,
  },
  102: { id: 102, specilization: 'Urheberrecht & Medienrecht', type: 1 },
  103: { id: 103, specilization: 'Vereinsrecht & Verbandsrecht', type: 1 },
  104: { id: 104, specilization: 'Verfassungsrecht', type: 1 },
  105: { id: 105, specilization: 'Vergaberecht', type: 1 },
  106: { id: 106, specilization: 'Verkehrsrecht', type: 1 },
  107: { id: 107, specilization: 'Versicherungsrecht', type: 1 },
  108: { id: 108, specilization: 'Verwaltungsrecht', type: 1 },
  109: { id: 109, specilization: 'Werkvertragsrecht', type: 1 },
  110: { id: 110, specilization: 'Wettbewerbsrecht', type: 1 },
  111: { id: 111, specilization: 'Wirtschaftsrecht', type: 1 },
  112: { id: 112, specilization: 'Zivilprozessrecht', type: 2 },
  113: { id: 113, specilization: 'Zivilrecht', type: 2 },
  114: { id: 114, specilization: 'Zwangsvollstreckungsrecht', type: 2 },
  115: { id: 115, specilization: 'Erbrecht', type: 2 },
  116: { id: 116, specilization: 'Familienrecht', type: 2 },
  117: { id: 117, specilization: 'Handelsrecht & Gesellschaftsrecht', type: 2 },
  118: { id: 118, specilization: 'Immobilienrecht', type: 2 },
  119: { id: 119, specilization: 'Vorsorgevollmacten', type: 2 },
  120: {
    id: 120,
    specilization: 'Sonstige Beglaubigungen & Beurkundung',
    type: 2,
  },
};

export const languages = [
  { id: 1, language: 'Arabisch' },
  { id: 2, language: 'Englisch' },
  { id: 3, language: 'Französisch' },
  { id: 4, language: 'Gebärdensprache' },
  { id: 5, language: 'Italienisch' },
  { id: 6, language: 'Persisch' },
  { id: 7, language: 'Polnisch' },
  { id: 8, language: 'Portugiesisch' },
  { id: 9, language: 'Rumänisch' },
  { id: 10, language: 'Russisch' },
  { id: 11, language: 'Spanisch' },
  { id: 12, language: 'Türkisc' },
];
