export const MARKER_CLICK = 'MARKER_CLICK';
export const ON_MOUSE_ENTER_CARD = 'ON_MOUSE_ENTER_CARD';
export const ON_MOUSE_LEAVE_CARD = 'ON_MOUSE_LEAVE_CARD';
export const GET_LAWYERS = 'GET_LAWYERS';
export const SET_LAWYERS = 'SET_LAWYERS';
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_LANGUAGE_FILTERS = 'SET_LANGUAGE_FILTERS';
export const SET_SPECIALIZATION_FILTERS = 'SET_SPECIALIZATION_FILTERS';
export const SEARCH_BY_NAME_OR_FIRM_OR_LOCATION = 'SEARCH_BY_NAME_OR_FIRM_OR_LOCATION';
export const GET_SEARCH_SUGGESTIONS_FOR_NAME_OR_FIRM = 'GET_SEARCH_SUGGESTIONS_FOR_NAME_OR_FIRM';
export const GET_SEARCH_SUGGESTIONS_FOR_LOCATIONS = 'GET_SEARCH_SUGGESTIONS_FOR_LOCATIONS';
export const GET_LAWYER_AVAILABILITY = 'GET_LAWYER_AVAILABILITY';
export const SET_LAWYER_AVAILABILITY = 'SET_LAWYER_AVAILABILITY';

export const specializations = {
  notarySpecializations: [
    { id: 112, specilization: 'Zivilprozessrecht', type: 2 },
    { id: 113, specilization: 'Zivilrecht', type: 2 },
    { id: 114, specilization: 'Zwangsvollstreckungsrecht', type: 2 },
    { id: 115, specilization: 'Erbrecht', type: 2 },
    { id: 116, specilization: 'Familienrecht', type: 2 },
    { id: 117, specilization: 'Handelsrecht & Gesellschaftsrecht', type: 2 },
    { id: 118, specilization: 'Immobilienrecht', type: 2 },
    { id: 119, specilization: 'Vorsorgevollmacten', type: 2 },
    { id: 120, specilization: 'Sonstige Beglaubigungen & Beurkundung', type: 2 },
  ],
  lawSpecializations: [
    { id: 1, specilization: 'Agrarrecht', type: 1 },
    { id: 2, specilization: 'Allgemeines Vertragsrecht', type: 1 },
    { id: 3, specilization: 'Anwaltshaftung', type: 1 },
    { id: 4, specilization: 'Arbeitsrecht', type: 1 },
    { id: 5, specilization: 'Arzthaftungsrecht', type: 1 },
    { id: 6, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
    { id: 7, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
    { id: 8, specilization: 'Baurecht & Architektenrecht', type: 1 },
    { id: 9, specilization: 'Beamtenrecht', type: 1 },
    { id: 10, specilization: 'Betreuungsrecht', type: 1 },
    { id: 11, specilization: 'Betriebliche Altersversorgung', type: 1 },
    { id: 12, specilization: 'Datenschutzrecht', type: 1 },
    { id: 13, specilization: 'Designrecht', type: 1 },
    { id: 14, specilization: 'Erbrecht', type: 1 },
    { id: 15, specilization: 'Familienrecht', type: 1 },
    { id: 16, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
    { id: 17, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
    { id: 18, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
    { id: 19, specilization: 'Insolvenzrecht', type: 1 },
    { id: 20, specilization: 'Internationales Recht', type: 1 },
    { id: 21, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
    { id: 22, specilization: 'IT-Recht', type: 1 },
    { id: 23, specilization: 'Jagdrecht', type: 1 },
    { id: 24, specilization: 'Kaufrecht', type: 1 },
    { id: 25, specilization: 'Maklerrecht', type: 1 },
    { id: 26, specilization: 'Markenrecht', type: 1 },
    { id: 27, specilization: 'Mediation', type: 1 },
    { id: 28, specilization: 'Medizinrecht', type: 1 },
    { id: 29, specilization: 'Mietrechts & Wohnungseigenturmsrecht', type: 1 },
    { id: 30, specilization: 'Migrationsrecht', type: 1 },
    { id: 31, specilization: 'Öffentliches Baurecht', type: 1 },
    { id: 32, specilization: 'Öffentliches Rechts', type: 1 },
    { id: 33, specilization: 'Opferhilfe', type: 1 },
    { id: 34, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
    { id: 35, specilization: 'Patentrecht', type: 1 },
    { id: 36, specilization: 'Pferderecht', type: 1 },
    { id: 37, specilization: 'Pflegerecht', type: 1 },
    { id: 38, specilization: 'Rechts rund ums Tier', type: 1 },
    { id: 39, specilization: 'Reiserecht', type: 1 },
    { id: 40, specilization: 'Schadensersatzrecht &', type: 1 },
    { id: 41, specilization: 'Schmerzensgeldrecht', type: 1 },
    { id: 42, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
    { id: 43, specilization: 'Secht', type: 1 },
    { id: 44, specilization: 'Schwerbehindertenrecht', type: 1 },
    { id: 45, specilization: 'Sozialrecht', type: 1 },
    { id: 46, specilization: 'Sozialversicherungsrecht', type: 1 },
    { id: 47, specilization: 'Sportrecht', type: 1 },
    { id: 48, specilization: 'Steuerrecht', type: 1 },
    { id: 49, specilization: 'StrafrechtAgrarrecht', type: 1 },
    { id: 50, specilization: 'Allgemeines Vertragsrecht', type: 1 },
    { id: 51, specilization: 'Anwaltshaftung', type: 1 },
    { id: 52, specilization: 'Arbeitsrecht', type: 1 },
    { id: 53, specilization: 'Arzthaftungsrecht', type: 1 },
    { id: 54, specilization: 'Ausländerrecht & Asylrecht', type: 1 },
    { id: 55, specilization: 'Bankrecht & Kapitalmarktrecht', type: 1 },
    { id: 56, specilization: 'Baurecht & Architektenrecht', type: 1 },
    { id: 57, specilization: 'Beamtenrecht', type: 1 },
    { id: 58, specilization: 'Betreuungsrecht', type: 1 },
    { id: 59, specilization: 'Betriebliche Altersversorgung', type: 1 },
    { id: 60, specilization: 'Datenschutzrecht', type: 1 },
    { id: 61, specilization: 'Designrecht', type: 1 },
    { id: 62, specilization: 'Erbrecht', type: 1 },
    { id: 63, specilization: 'Familienrecht', type: 1 },
    { id: 64, specilization: 'Forderungseinzug & Inkassorecht', type: 1 },
    { id: 65, specilization: 'Gewerblicher Rechtsschutz', type: 1 },
    { id: 66, specilization: 'Grundstücksrechts & Immobilienrecht', type: 1 },
    { id: 67, specilization: 'Insolvenzrecht', type: 1 },
    { id: 68, specilization: 'Internationales Recht', type: 1 },
    { id: 69, specilization: 'Internationales Wirtschaftsrecht', type: 1 },
    { id: 70, specilization: 'IT-Recht', type: 1 },
    { id: 71, specilization: 'Jagdrecht', type: 1 },
    { id: 72, specilization: 'Kaufrecht', type: 1 },
    { id: 73, specilization: 'Maklerrecht', type: 1 },
    { id: 74, specilization: 'Markenrecht', type: 1 },
    { id: 75, specilization: 'Mediation', type: 1 },
    { id: 76, specilization: 'Medizinrecht', type: 1 },
    { id: 77, specilization: 'Mietrechts & Wohnungseigenturmsrecht', type: 1 },
    { id: 78, specilization: 'Migrationsrecht', type: 1 },
    { id: 79, specilization: 'Öffentliches Baurecht', type: 1 },
    { id: 80, specilization: 'Öffentliches Rechts', type: 1 },
    { id: 81, specilization: 'Opferhilfe', type: 1 },
    { id: 82, specilization: 'Ordnungswidrigkeitenrecht', type: 1 },
    { id: 83, specilization: 'Patentrecht', type: 1 },
    { id: 84, specilization: 'Pferderecht', type: 1 },
    { id: 85, specilization: 'Pflegerecht', type: 1 },
    { id: 86, specilization: 'Rechts rund ums Tier', type: 1 },
    { id: 87, specilization: 'Reiserecht', type: 1 },
    { id: 88, specilization: 'Schadensersatzrecht &', type: 1 },
    { id: 89, specilization: 'Schmerzensgeldrecht', type: 1 },
    { id: 90, specilization: 'Schiedsgerichtsbarkeit', type: 1 },
    { id: 91, specilization: 'Secht', type: 1 },
    { id: 92, specilization: 'Schwerbehindertenrecht', type: 1 },
    { id: 93, specilization: 'Sozialrecht', type: 1 },
    { id: 94, specilization: 'Sozialversicherungsrecht', type: 1 },
    { id: 95, specilization: 'Sportrecht', type: 1 },
    { id: 96, specilization: 'Steuerrecht', type: 1 },
    { id: 97, specilization: 'Strafrecht', type: 1 },
    { id: 98, specilization: 'Transportrecht & Speditionsrecht', type: 1 },
    { id: 99, specilization: 'Umweltrecht', type: 1 },
    { id: 100, specilization: 'Unterhaltsrecht', type: 1 },
    { id: 101, specilization: 'Unternehmensrecht & Betriebsnachfolge', type: 1 },
    { id: 102, specilization: 'Urheberrecht & Medienrecht', type: 1 },
    { id: 103, specilization: 'Vereinsrecht & Verbandsrecht', type: 1 },
    { id: 104, specilization: 'Verfassungsrecht', type: 1 },
    { id: 105, specilization: 'Vergaberecht', type: 1 },
    { id: 106, specilization: 'Verkehrsrecht', type: 1 },
    { id: 107, specilization: 'Versicherungsrecht', type: 1 },
    { id: 108, specilization: 'Verwaltungsrecht', type: 1 },
    { id: 109, specilization: 'Werkvertragsrecht', type: 1 },
    { id: 110, specilization: 'Wettbewerbsrecht', type: 1 },
    { id: 111, specilization: 'Wirtschaftsrecht', type: 1 },
  ],
};

export const languages = [
  { id: 1, language: 'Arabisch' },
  { id: 2, language: 'Englisch' },
  { id: 3, language: 'Französisch' },
  { id: 4, language: 'Gebärdensprache' },
  { id: 5, language: 'Italienisch' },
  { id: 6, language: 'Persisch' },
  { id: 7, language: 'Polnisc' },
  { id: 8, language: 'Portugiesisc' },
  { id: 9, language: 'Rumänisch' },
  { id: 10, language: 'Russisch' },
  { id: 11, language: 'Türkisc' },
];
